schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "sprite_sheet_exporter"
version = "0.0.5"
name = "Sprite Sheet Exporter"
tagline = "Export your spite sheets with ease"
maintainer = "HorryPortier https://github.com/Horryportier/"
# Supported types: "add-on", "theme"
type = "add-on"

website = "https://extensions.blender.org/approval-queue/sprite-sheet-exporter/"

tags = ["Render", "Import-Export"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
# # Optional: required by some licenses.
# copyright = [
#   "2002-2024 Developer Name",
#   "1998 Company Name",
# ]

# # Optional: list of supported platforms. If omitted, the extension will be available in all operating systems.
platforms = ["windows-x64", "linux-x64"]
# # Other supported platforms: "windows-arm64", "macos-x64"

wheels = [
	"./wheels/pillow-10.3.0-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/pillow-10.3.0-cp311-cp311-manylinux_2_28_x86_64.whl",
	"./wheels/pillow-10.3.0-cp311-cp311-win_amd64.whl",
]

# # Optional: add-ons can list which resources they will require:
# # * files (for access of any filesystem operations)
# # * network (for internet access)
# # * clipboard (to read and/or write the system clipboard)
# # * camera (to capture photos and videos)
# # * microphone (to capture audio)
# #
# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #
# # For each permission it is important to also specify the reason why it is required.
# # Keep this a single short sentence without a period (.) at the end.
# # For longer explanations use the documentation or detail page.
#
[permissions]
# network = "Need to sync motion-capture data to server"
files = "Import/export  exporting files, clearing output directory"
# clipboard = "Copy and paste bone transforms"

# # Optional: advanced build settings.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# # These are the default build excluded patterns.
# # You only need to edit them if you want different options.
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]
